# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
        ('updater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('no_encontrado', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='bankupdatefile',
            name='cobrar_colegiacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bankupdatefile',
            name='cuenta_colegiacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colegiacion_set', to='bridge.Account'),
        ),
        migrations.AddField(
            model_name='bankupdatefile',
            name='cuenta_excedente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excedente_set', to='bridge.Account'),
        ),
        migrations.AddField(
            model_name='bankupdatefile',
            name='cuenta_prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamo_set', to='bridge.Account'),
        ),
        migrations.AddField(
            model_name='bankupdatefile',
            name='usar_id',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='errorlectura',
            name='bank_update_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updater.BankUpdateFile'),
        ),
    ]
