# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bridge', '0002_auto_20160426_0952'),
        ('updater', '0002_auto_20160405_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionUpdateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('archivo', models.FileField(upload_to='update/%Y/%m/%d')),
                ('fecha_de_cobro', models.DateField()),
                ('fecha_de_procesamiento', models.DateField()),
                ('procesado', models.BooleanField(default=False)),
                ('usar_id', models.BooleanField(default=True)),
                ('cobrar_colegiacion', models.BooleanField(default=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Cotizacion')),
                ('cuenta_colegiacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colegiacion_cotizacion_set', to='bridge.Account')),
                ('cuenta_excedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excedente_cotizacion_set', to='bridge.Account')),
                ('cuenta_prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamo_cotizacion_set', to='bridge.Account')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='ErrorLecturaCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('no_encontrado', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotizacion_update_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updater.CotizacionUpdateFile')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
