# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_auto_20160426_0952'),
        ('updater', '0003_cotizacionupdatefile_errorlecturacotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparacionBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('archivo', models.FileField(upload_to='compare/%Y/%m/%d')),
                ('usar_id', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Banco')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='DiferenciaBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deducciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_en_archivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('afiiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Affiliate')),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updater.ComparacionBanco')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
