# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_auto_20160426_0952'),
        ('updater', '0006_errorcomparacionbanco'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiferenciaCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deducciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_en_archivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('afiiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Affiliate')),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updater.CotizacionUpdateFile')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ErrorComparacionCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('no_encontrado', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updater.CotizacionUpdateFile')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='bankupdatefile',
            name='archivo',
            field=models.FileField(upload_to='update//%Y/%m/%d'),
        ),
    ]
